// Help text configuration for all analytics metrics

export const ANALYTICS_HELP = {
  totalRevenue: {
    title: "Total Revenue",
    description: "Sum of all revenue generated by paid orders in the selected period.",
    details: [
      "Only counts orders with 'paid' payment status",
      "Does not include pending, cancelled, or failed orders"
    ],
    formula: "Sum of total_amount where payment_status = 'paid'"
  },
  revenueGrowth: {
    title: "Revenue Growth",
    description: "Percentage growth or decline of revenue compared to the previous period.",
    details: [
      "Compares current period revenue vs previous period of same size",
      "Positive value (+) indicates growth",
      "Negative value (-) indicates decline"
    ],
    formula: "((Current Revenue - Previous Revenue) / Previous Revenue) × 100"
  },
  totalOrders: {
    title: "Total Orders",
    description: "Total number of orders placed in the selected period, regardless of payment status.",
    details: [
      "Includes all orders (paid, pending, cancelled)"
    ],
    formula: "COUNT(orders) in the period"
  },
  totalCustomers: {
    title: "Total Customers",
    description: "Total number of customers registered in the system.",
    details: [
      "Counts all profiles in the database"
    ],
    formula: "COUNT(profiles)"
  },
  conversionRate: {
    title: "Conversion Rate",
    description: "Relationship between orders placed and new customers registered in the period.",
    details: [
      "Measures how effective the system is at converting new registrations into sales"
    ],
    formula: "(Total Orders / New Customers) × 100"
  },
  salesTrend: {
    title: "Sales Trend",
    description: "Shows the evolution of revenue during the selected period.",
    details: [
      "Only counts paid orders (payment_status = 'paid')"
    ]
  },
  customerAcquisition: {
    title: "Customer Acquisition",
    description: "Shows how many new customers registered during the selected period.",
    details: [
      "Based on profile creation date (created_at)"
    ]
  },
  orderStatus: {
    title: "Order Status",
    description: "Distribution of orders according to their current status.",
    details: [
      "Pending: Orders created but not processed",
      "Processing: Orders being prepared",
      "Shipped: Orders dispatched but not delivered",
      "Delivered: Completed orders",
      "Cancelled: Cancelled orders"
    ]
  },
  customerSegmentation: {
    title: "Customer Segmentation",
    description: "Classification of customers according to their membership type or status.",
    details: [
      "Members: Customers with active membership",
      "Premium: Customers with premium membership",
      "Basic: Customers with basic membership",
      "No Membership: Registered customers without membership"
    ]
  },
  categoryRevenue: {
    title: "Revenue by Category",
    description: "Shows which product categories generate the most revenue.",
    details: [
      "Calculated by summing total price of all items sold by category"
    ],
    formula: "Sum of (quantity × price) by product category"
  },
  topProducts: {
    title: "Top Products",
    description: "Ranking of products that have generated the most revenue in the period.",
    details: [
      "Ordered by total revenue (quantity × price)",
      "Only shows top products"
    ],
    formula: "Sum of total_price grouped by product_id"
  }
};

export const EMPTY_STATE_MESSAGES = {
  noOrders: {
    title: "No orders registered",
    message: "No orders have been registered in the system yet.",
    suggestion: "You can create orders manually from the Orders section."
  },
  noProducts: {
    title: "No products sold",
    message: "No products have been sold in the selected period.",
    suggestion: "Try selecting a wider period (90 or 365 days) or verify you have active products in the catalog."
  },
  noCustomers: {
    title: "No new customers",
    message: "No new customers registered in this period.",
    suggestion: "Customers can register from the website or you can create them manually from the Customers section."
  },
  noCategories: {
    title: "No categories with sales",
    message: "Categories will appear when you have products sold assigned to categories.",
    suggestion: "Make sure your products have categories assigned in the catalog."
  }
};

